---
title: "Subway Ridership Overtime"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(shiny)
library(leaflet)
library(sf)
library(rgdal)
library(viridis)
```

```{r loading data, include=FALSE}
turnstiles_data = read_csv("./data/shiny_data.csv") %>% 
    drop_na()

pal = colorNumeric(palette = "viridis", domain = turnstiles_data$turnstile_count) 

subway_lines = st_read(
    "./data/subway_lines_data/geo_export_cef610e7-3c97-412c-ac0a-44a37bcf4f9b.shp")

subway_lines = st_transform(subway_lines, CRS("+proj=longlat +ellps=GRS80 +datum=WGS84")) 
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
sliderInput("date", 
            label = h3("Date Range"), 
            min = as.Date("2019-01-01","%Y-%m-%d"),
            max = as.Date("2019-07-01","%Y-%m-%d"),
            value  = as.Date("2019-03-03","%Y-%m-%d"),
            timeFormat = "%d %b %y",
            step = 7,
            animate = animationOptions(interval = 500, loop = FALSE),
            ticks = F)
        
checkboxGroupInput("borough_choice", label = h3("NYC Borough"), 
                   choices = c("Queens", "Brooklyn", "Bronx", "Manhattan", "Staten Island"),
                   selected = "Manhattan")
        
radioButtons("turnstile_type_choice", label = h3("Turnstile Data"),
           choices = c("exits", "entries"), 
           selected = "exits")
```

Column
-----------------------------------------------------------------------

```{r}
### Subway Map

selectedData = reactive({
        turnstiles_data %>% 
            filter(
                turnstile_type == input$turnstile_type_choice &
                borough %in% input$borough_choice &
                date >= as.Date(input$date, "%Y-%m-%d"))
    })
    
renderLeaflet({
    nyc_map = leaflet(selectedData()) %>% 
        setView(-74.00, 40.78, zoom = 11) %>%
        addProviderTiles("CartoDB.Positron") %>% 
        addPolylines(data = subway_lines, color = "red", opacity = 0.2) %>%
        addCircleMarkers(
            data = selectedData(),
            lat = ~ gtfs_latitude, 
            lng = ~ gtfs_longitude, 
            radius = 3,
            color = ~ pal(turnstile_count),
            stroke = FALSE, 
            fillOpacity = 0.85) %>% 
    addLegend("bottomright", pal = pal,
              values = ~ turnstile_count,
              title = "Ridership",
              opacity = 1)
})
```
